### PR TITLE
Extending the functionality of the Chatter API wrapper by adding two …

### PR DESCRIPTION
**Pull request by nmonasterio**
…new methods:

- The ability to post directly to a particular object (such as opportunity or account) rather than to news or me. This is accomplished through the PostFeedItemToObjectAsync method.

- The ability to post a file to a particular object with Chatter, by passing the byte array of the file contents as well as some content for it. This is accomplished through the PostFeedItemWithAttachmentAsync method.

Adds a few classes to extend the property requirements of FeedItem, such as Capabilities and Content.

I'm also adding an extra method to the HTTPservice implementation, which allows for binary data to be sent alongside a JSON payload when uploading files.

### CODE REVIEW

**Comment by nmonasterio** [comment]
Hi Wade,

I hope all's well with you. I just wanted to drop you a quick note regarding your .NET toolkit for SFDC. It has been a fantastic wrapper for  interacting with the API.
I made a few commits to your repo, which extend the functionality of the Chatter API by allowing it to post to objects directly as well as posting files to them.  A quick note, however: I pushed some commits to the pull request I made, but the functional tests were bombing out me because they were either using the v30.0 version of the API, which have slightly different endpoints, or there are no groups available for retrieving groups or there are no objects for me to post to.
Anyway, I'm more than happy to contribute further to updating all the endpoints to >32.0, but I just wanted you to be aware of it because of the potential breaks in the functional testing.
Let me know if there's anything I can help you with. Happy to contribute. Very grateful for the work you've done.

**Comment by wadewegner** [comment]
Sorry for the lack of response! Thank you so much for the contribution. I've not been as active lately and am in the process of getting @dcarroll comfortable supporting the toolkit. I'll try to merge and test this out soon and see if we can apply your updates.

Thanks!

**Comment by nmonasterio** [comment]
No problem at all, Wade. Just let me know if you have any questions. If you would like me to step in and help @dcarroll as well with it, I'm more than happy to. I've been using the heck out of it and have some ideas on how to add more functionality to it. It has been a great library to refer to.

Just let me know. Thanks much!

**Comment by dcarroll** [comment]
Hi Napo,

Check out some of the enhancements that I have in progress in my fork here
https://github.com/dcarroll/Force.com-Toolkit-for-NET/tree/unstable

Let me know what you think.

On Tue, Jun 23, 2015 at 4:29 PM, Napo Monasterio <notifications@github.com>
wrote:

> No problem at all, Wade. Just let me know if you have any questions. If
> you would like me to step in and help @dcarroll
> <https://github.com/dcarroll> as well with it, I'm more than happy to.
> I've been using the heck out of it and have some ideas on how to add more
> functionality to it. It has been a great library to refer to.
>
> Just let me know. Thanks much!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/114#issuecomment-114673703>
> .
>



-- 
Thanks,
Dave

**Comment by nmonasterio** [comment]
Looking good, @dcarroll ! Nice refactoring in some areas over there. Let me know if there's anything in particular you need help with, and I'm happy to fork it out and help out.

Good work, sir!

**Comment by wadewegner** [comment]
Where are we on this one, @dcarroll? I'm happy to review the code if you think there's value to pulling this in.

**Comment by wadewegner** [comment]
Looks pretty solid to me; would require a bit of refactoring at this point, but certainly doable. Thanks again @nmonasterio!

**Comment by nmonasterio** [comment]
Cool. Let me know what else you two might need. Happy to do any refactoring on my end as well, and I'll check as well to see if there is any extra functionality that might need to be added.

Thank you both!

**Comment by dcarroll** [comment]
I would like to get this in as it makes the toolkit more future proof.

On Mon, Aug 24, 2015 at 6:54 PM, Napo Monasterio <notifications@github.com>
wrote:

> Cool. Let me know what else you two might need. Happy to do any
> refactoring on my end as well, and I'll check as well to see if there is
> any extra functionality that might need to be added.
>
> Thank you both!
>
> Sent from my Nintendo Gameboy
>
> > On Aug 24, 2015, at 7:38 PM, Wade Wegner <notifications@github.com>
> wrote:
> >
> > Looks pretty solid to me; would require a bit of refactoring at this
> point, but certainly doable. Thanks again @nmonasterio!
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/114#issuecomment-134443933>
> .
>



-- 
Thanks,
Dave

**Comment by wadewegner** [comment]
Reviewing ...

**Comment by wadewegner** [comment]
It was a bit complicated trying to merge has @dcarroll had made updates to the Chatter client more recently. I think this commit https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/a498e59f1e3838a0648b49c3273b13562a00972c reflects a good merge of the two. Can you both review?

**Pull request merged**
