### PR TITLE
Added ability to get latest version.

### PR DESCRIPTION
**Pull request by Tennyleaz**
Added a method to get latest Salesforce api version form Salesforce instance url, and automatically update the `ApiVersion` string in authentication client.

### CODE REVIEW

**Comment by wadewegner** [comment]
Thanks, @Tennyleaz.

This looks good and builds, but unless I'm missing something, it's not used. Can you share an example or test that highlights the functionality?

**Comment by Tennyleaz** [comment]
In the past, if I login like:

    var authClient = new AuthenticationClient();
    await authClient.UsernamePasswordAsync(clientID, clientSecret, username, password);
    var forceClient = new ForceClient(authClient.InstanceUrl, authClient.AccessToken, authClient.ApiVersion);

The API version of `ForceClient` will be "v36.0" in default, or the user have to manually set in `AuthenticationClient` constructor.

My new method added the ability to get latest version from Salesforce server:

    var authClient = new AuthenticationClient();
    await authClient.UsernamePasswordAsync(clientID, clientSecret, username, password);
    await authClient.GetLatestVersionAsync();  // get from https://yourInstance.salesforce.com/services/data/
    var forceClient = new ForceClient(authClient.InstanceUrl, authClient.AccessToken, authClient.ApiVersion);

So one could use the latest api version automatically.

**Comment by wadewegner** [comment]
@Tennyleaz Got it. Sounds good!

**Comment by wadewegner** [comment]
I'll merge. If you could send a PR with an update to the README.md that'd be awesome.

**Comment by Tennyleaz** [comment]
@wadewegner Sure, I could update README when I have spare time.

**Pull request merged**
