### PR TITLE
Allow callers to manage HttpClient life cycle and disposal.

### PR DESCRIPTION
**Pull request by jrsteele23**
Not gonna lie. I'm new to actually committing and merging repos via GitHub. Please let me know what I'm doing wrong. This pull request is to address issue #335. I'm not sure how to tie this pull request to an issue. Thanks!

### CODE REVIEW

**Comment by jrsteele23** [comment]
Well CI is failing and I don't understand what or why the tests are broken. I'm not going to shotgun changes in an attempt to guess. Further direction and insight is very welcomed. Thanks!

**Comment by marknadig** [comment]
@jrsteele23 if you look at the other PRs you will see CI has just been failing. I had an update to readme and it failed :/
https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/321

**Comment by wadewegner** [comment]
Looking shortly. Thanks, @jrsteele23 and @marknadig.

**Comment by wadewegner** [comment]
Thank you for the contribution, @jrsteele23!

**Pull request merged**
