### PR TITLE
Add ability to query blob object contents

### PR DESCRIPTION
**Pull request by samtrost-avalara**
Example usage would be to get attachment contents out of SalesForce.

forceClient.GetBlobAsync("Attachment", attachmentId, "Body");

### CODE REVIEW

**Comment by wadewegner** [comment]
Can you add a unit test?

**Comment by Nickwwest** [comment]
Would be great to get this merged, it seems low-risk

**Comment by devshane** [comment]
@wadewegner Is it possible to fetch Blob data without this PR? I'd like to save the contents of `Attachment.Body` to a local file but can't quite figure out how I should request it.

@Nickwwest were you able to accomplish this another way?

**Comment by wadewegner** [comment]
Thanks @samtrost-avalara for the contribution. @Nickwwest and @devshane this will be in the next package.

**Pull request merged**
