### PR TITLE
Fixing how Custom Rest URl's are generated

### PR DESCRIPTION
**Pull request by bluephlame**
The FormatCustom URL was returning a string and therefore did not call
the correct HttpGetAsync<>() method. calling the string overload instead
of the Uri overload.  changing the type now to be a Uri will fix this.

This fixes issue  #130

### CODE REVIEW

**Comment by wadewegner** [comment]
This looks cool. @bluephlame, do you have a simple test I can write that would work against a default Developer org?

**Comment by bluephlame** [comment]
@wadewegner I actually dont know how to set that up.  As this is referring to custom build REST endpoints, and by definition Custom REST services are not in default developer orgs.

I can tell you that we are using this branch in our own nuGET package. 

I am also not sure of the commits that are being shown here.  As I have made some changes to our fork that are now showing up here.  These will affect the build scripts.  I may need some guidance in how to remove them.  The only two commits you should worry about are 2f88a0f and f3449d0

**Comment by wadewegner** [comment]
Don't worry about some of those commits. I can get rid of them during the merge.

I'm going to explore how to test your addition. It looks useful!

**Comment by dcarroll** [comment]
We can easily create a custom REST service in the test org for this.

Dave Carroll

On Aug 25, 2015, at 8:24 PM, Wade Wegner <notifications@github.com> wrote:

Don't worry about some of those commits. I can get rid of them during the
merge.

I'm going to explore how to test your addition. It looks useful!

—
Reply to this email directly or view it on GitHub
<https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/131#issuecomment-134807813>
.

**Comment by wadewegner** [comment]
@dcarroll Would be awesome if you'd do that sir! =) Tell me what you create, and I'll create the appropriate tests.

**Comment by dcarroll** [comment]
Ok, I've created a simple custom get and custom post for a single endpoint.
Here is the url:
https://na10.salesforce.com/services/apexrest/RestWSTest/

The get returns a string containing the word "stuff".
The post echos what was sent. It expects a json payload like:
{ "toecho":"Thing to echo" }

**Comment by wadewegner** [comment]
Cool! Trying it out now.

**Comment by wadewegner** [comment]
Refactored and added a test which work! Thank you both. Here's the commit: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/83e4ef8accdd7113f471f29d3d4501828add4aed

Take a look. It will be a part of the next NuGet release.

As an aside, I'm not happy with the way `ServiceHttpClient` is going. At some point we're going to have to look closely at it and make some changes. I'm beginning to think that collapsing everything together (rather than having multiple layers) is a better approach.

**Comment by wadewegner** [comment]
In looking at this issue https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/130 I realized there was some additional optimizations required. I've fixed and added as part of this commit: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/2608a002e40b89c3bc21dae7def58b97a624a77a

**Comment by dcarroll** [comment]
Ah, right! Nice catch!

On Wed, Aug 26, 2015 at 1:51 PM, Wade Wegner <notifications@github.com>
wrote:

> In looking at this issue #130
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/issues/130>
> I realized there was some additional optimizations required. I've fixed and
> added as part of this commit: 2608a00
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/2608a002e40b89c3bc21dae7def58b97a624a77a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/131#issuecomment-135167069>
> .
>



-- 
Thanks,
Dave

**Pull request merged**
